name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
    - name: Sleep for a while
      uses: jakejarvis/wait-action@master
      with:
        time: '3s'
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        deploy_key: ${{ secrets.DEPLOY_TO_GITHUB_IO }}
        external_repository: wudanyang6/wudanyang6.github.io
        publish_branch: gh-pages-turbo
        publish_dir: ./dist
