name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
      
    # - name: Deploy to dist directory
    #   run: |
    #     git config --local user.email "wu.danyang@qq.com"
    #     git config --local user.name "wudanyang6"
    #     git add dist -f
    #     git commit -m "Deploy website contents to dist" -a  # 提交改动
    #     git push  # 推送到远端仓库
        
    # - name: Push changes
    #   uses: ad-m/github-push-action@v0.8.0
    #   with:
    #     branch: gh-page
    #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #     github_url: https://github.com/
    #     directory: dist
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        deploy_key: ${{ secrets.DEPLOY_TO_GITHUB_IO }}
        external_repository: wudanyang6/wudanyang6.github.io
        publish_branch: gh-pages-turbo
        publish_dir: ./dist

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   # - name: Copy build artifacts to dist directory
  #   #   run: |
  #   #     mkdir dist
  #   #     cp -r dist/* dist/

  #   - name: Commit and push changes
  #     uses: stefanzweifel/git-auto-commit-action@v4
  #     with:
  #       commit_message: "Auto deploy static site [skip ci]"

  #   - name: Push changes
  #     uses: ad-m/github-push-action@v0.8.0
  #     with:
  #       branch: gh-page
  #       github_token: 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
  #       github_url: https://github.com/dy_turbo/
  #       directory: .
